### ISSUE TITLE
update Roger Wireless SMS & remove Ting

### ISSUE THREAD

**Issue by chadmcinnis** [cubiclesoft/email_sms_mms_gateways#14]
Per [Roger Wireless](https://www.rogers.com/customer/support/article/set-up-email-to-text) - SMS should be @pcs.rogers.com
> Your email address will be your 10-digit Rogers wireless phone number followed by @pcs.rogers.com. Example: [area code and phone number]@pcs.rogers.com

Per [Ting Support](https://help.ting.com/hc/en-us/articles/205421938-Text-Messaging#:~:text=On%20CDMA%20devices%2C%20use%20the,text%20message%20to%20your%20device) - Email to text is not supported
> IMPORTANT: Our network partners do not provide service level guarantees for email-to-SMS messaging delivery. As a result, the email-to-text functionality is unsupported on the Ting network. This service may not work correctly, or at all, with certain devices and/or conditions

**Comment by cubiclesoft** [comment]
The domain `pcs.rogers.com` does not exist in DNS.  However, `sms.rogers.com` and `mms.rogers.com` do exist.  Their own documentation is obviously wrong.

Ting domain removed due to no longer resolving in DNS.  In general, "unsupported" is not the same thing as "non-functional" though.  Ting is a MVNO.  That means using the appropriate email gateway may still reach the device.

That said, I prefer SignalWire or Twilio for reliable SMS/MMS delivery.  I wrote a fully functional [PHP SDK for SignalWire/Twilio](https://github.com/cubiclesoft/php-twilio-sdk) a while back.  If the goal is Two-Factor Authentication (2FA), reverse 2FA on SignalWire is free (i.e. the user sends the 2FA code from their phone to the server instead of doing the reverse).

**Comment by cubiclesoft** [comment]
Whoops.  `message.ting.com` does exist as a MX record but not an A record in DNS.  I'm reverting the change that was made today.

`pcs.rogers.com` also exists as a MX record.  There are complaints about that domain though as being very slow in delivery (1-2 minutes) compared to `sms.rogers.com` (5-15 seconds) but more reliable.
